### ISSUE TITLE
improve install instructions

### ISSUE THREAD

**Issue by marcmerlin** [benpicco/FastLEDonPc#1]
I gave it a shot. First, things didn't work 
/home/merlin/arduino/prg/Neopixel/FastLEDonPc/example/hello_world/hello.ino:1:10: fatal error: Adafruit_GFX.h: No such file or directory
 #include <Adafruit_GFX.h>

make print showed I had include directories that were empty, ah, I see git submodule was needed it seems
```
saruman:~/prg/arduino/Neopixel/FastLEDonPc$ git submodule init
saruman:~/prg/arduino/Neopixel/FastLEDonPc$ git submodule update
Cloning into '/home/merlin/arduino/prg/Neopixel/FastLEDonPc/libraries/Adafruit-GFX'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
fatal: clone of 'git@github.com:adafruit/Adafruit-GFX-Library.git' into submodule path '/home/merlin/arduino/prg/Neopixel/FastLEDonPc/libraries/Adafruit-GFX' failed
```
I'm not too sure how this was supposed to work. can you help?

**Comment by benpicco** [comment]
Ah thank you! I used ssh addresses for the submodules, but you can only access these if you have registered your ssh key with GitHub - I pointed them to the https version instead, it should work now. (You will probably have to check out the repository again)
